---
abstract: 'Get/Validate data from credit & debit cards'
author:
  - 'Simon Elliott <cpan@papercreatures.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200005, CPAN::Meta::Converter version 2.110330'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Business-CardInfo
requires:
  Moose: 0
  Test::Role: 0
version: 0.10
