---
abstract: 'Get/Validate data from credit & debit cards'
author:
  - 'Simon Elliott <cpan@papercreatures.com>'
generated_by: 'Dist::Zilla version 1.100160'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Business-CardInfo
requires:
  ExtUtils::MakeMaker: 6.11
  Moose: 0
  Test::Role: 0
version: 0.03
